//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPOMTrackingVaccine.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vaksindbEntities2 : DbContext
    {
        public vaksindbEntities2()
            : base("name=vaksindbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<laporanvaksin> laporanvaksin { get; set; }
        public virtual DbSet<pasien> pasien { get; set; }
        public virtual DbSet<pelaporan_penggunaan> pelaporan_penggunaan { get; set; }
        public virtual DbSet<produsen> produsen { get; set; }
        public virtual DbSet<rumah_sakit> rumah_sakit { get; set; }
        public virtual DbSet<vaksin> vaksin { get; set; }
    }
}
