//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPOMTrackingVaccine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasien
    {
        public string noRegPasien { get; set; }
        public string nikPasien { get; set; }
        public string noRekamMedis { get; set; }
        public string namaPasien { get; set; }
        public string alamatPasien { get; set; }
        public string idPemerintah { get; set; }
        public string noRegVaksin { get; set; }
        public string idRS { get; set; }
        public string noTelepon { get; set; }
    }
}
