//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPOMTrackingVaccine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rumah_sakit
    {
        public string idRS { get; set; }
        public string namaRS { get; set; }
        public string alamatRS { get; set; }
        public long nikPasien { get; set; }
        public string noTelepon { get; set; }
        public string noRegVaksin { get; set; }
    }
}
