//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfRumahSakit
{
    using System;
    using System.Collections.Generic;
    
    public partial class bpom
    {
        public string idBPOM { get; set; }
        public string noTelepon { get; set; }
        public string alamatBPOM { get; set; }
    }
}
