//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfRumahSakit
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelaporan_penggunaan
    {
        public string idPelaporanP { get; set; }
        public string idBPOM { get; set; }
        public string idRS { get; set; }
        public string noRegVaksin { get; set; }
        public string nikPasien { get; set; }
        public string noRekamMedis { get; set; }
        public string statusV { get; set; }
    }
}
