//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfProdusen
{
    using System;
    using System.Collections.Generic;
    
    public partial class laporanvaksin
    {
        public int idLaporan { get; set; }
        public string noRegVaksin { get; set; }
        public string idProdusen { get; set; }
        public string idBPOM { get; set; }
        public string status { get; set; }
    }
}
