//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProduceTrackingVaccine.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="laporanvaksin", Namespace="http://schemas.datacontract.org/2004/07/WcfProdusen")]
    [System.SerializableAttribute()]
    public partial class laporanvaksin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idBPOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idLaporanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProdusenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string noRegVaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idBPOM {
            get {
                return this.idBPOMField;
            }
            set {
                if ((object.ReferenceEquals(this.idBPOMField, value) != true)) {
                    this.idBPOMField = value;
                    this.RaisePropertyChanged("idBPOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLaporan {
            get {
                return this.idLaporanField;
            }
            set {
                if ((this.idLaporanField.Equals(value) != true)) {
                    this.idLaporanField = value;
                    this.RaisePropertyChanged("idLaporan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProdusen {
            get {
                return this.idProdusenField;
            }
            set {
                if ((object.ReferenceEquals(this.idProdusenField, value) != true)) {
                    this.idProdusenField = value;
                    this.RaisePropertyChanged("idProdusen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string noRegVaksin {
            get {
                return this.noRegVaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.noRegVaksinField, value) != true)) {
                    this.noRegVaksinField = value;
                    this.RaisePropertyChanged("noRegVaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLaporanVaksin", ReplyAction="http://tempuri.org/IService1/AddLaporanVaksinResponse")]
        bool AddLaporanVaksin(ProduceTrackingVaccine.ServiceReference1.laporanvaksin data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLaporanVaksin", ReplyAction="http://tempuri.org/IService1/AddLaporanVaksinResponse")]
        System.Threading.Tasks.Task<bool> AddLaporanVaksinAsync(ProduceTrackingVaccine.ServiceReference1.laporanvaksin data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProduceTrackingVaccine.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProduceTrackingVaccine.ServiceReference1.IService1>, ProduceTrackingVaccine.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddLaporanVaksin(ProduceTrackingVaccine.ServiceReference1.laporanvaksin data) {
            return base.Channel.AddLaporanVaksin(data);
        }
        
        public System.Threading.Tasks.Task<bool> AddLaporanVaksinAsync(ProduceTrackingVaccine.ServiceReference1.laporanvaksin data) {
            return base.Channel.AddLaporanVaksinAsync(data);
        }
    }
}
